### ISSUE TITLE
FAN,HAIKU,*SERIES not being identified as a valid device

### ISSUE THREAD

**Issue by vivienne** [vivienne/homebridge-haiku-senseme#3]
Hi Folks..
Unfortunately the plugin didn't work for me. I removed "the old" BAF in config.json and added yours by config-ui-ix.

```
{
            "name": "Deckenventilator",
            "platform": "haiku"
        }
```

After homebridge restart no Fan is showing up at all. 
I hope you are able to fix this. Would love to switch to your plugin. 
Thanks in advance.

2017 Product Code K3127-S0-PW-09-02-C-01
Product Name Haiku Ceiling Fan, I Series, 52 Inches, Low Profile Mount, No Light
White Airfoils, White Motor, (<125W), ( CZ, **GER**, IT ), (U), 0.019HP, 100-125, 200-240 VAC, Single Phase

![Napkin 07 10 20, 9 53 05 AM](https://user-images.githubusercontent.com/3874239/95303001-f38ff280-0882-11eb-82cd-d9d4a4ba28e4.png)

```
[2020-10-7 9:45:50] [Deckenventilator] Found a device: Ventilator / FAN,HAIKU,HSERIES / 192.168.178.32 / 20:F8:5E:F6:C0:82
[2020-10-7 9:45:50] [Deckenventilator] Not sure what to do with this device type: Ventilator (FAN,HAIKU,HSERIES)
: SenseME discovery server shutting down
```

_Originally posted by @DJay-X in https://github.com/vivienne/homebridge-haiku-senseme/issues/2#issuecomment-704763227_

**Comment by vivienne** [comment]
@DJay-X @dsully I pushed a change to treat all devices identifying themselves starting with FAN,HAIKU as fans. I don't have a fan to test it on myself, can you give it a try and let me know if it works? I've published it as v2.0.1.

**Comment by dsully** [comment]
Ok. I also posted a change in https://github.com/vivienne/haiku-senseme/pull/1 that could be consumed here to address.

**Comment by vivienne** [comment]
Thank you! Do different series of the fans have different features that would change how we should treat them in the plugin? If so then I should probably test your commit and go that route. If not I'm inclined to be lazy and just leave it the way it is (assuming that my patch works).

**Comment by vivienne** [comment]
Thank you! Do different series of the fans have different features that would change how we should treat them in the plugin? If so then I should probably test your commit and go that route. If not I'm inclined to be lazy and just leave it the way it is (assuming that my patch works).

**Comment by dsully** [comment]
I only have the original Haiku, so I'm not sure about different features.

**Comment by DJay-X** [comment]
Thanks. Is now working. Kind of. 
But the status on/off is not showing up in Home or Eve App even when the Fan is on. 
I can turn it on/off in the app and of course then it's working.
But when the Fan is already running and I open the App the switch is showing off.
Also when adjusting the speed the fan responds to that change and is running but the switch is still off. 
The switch is not automatically refreshing/loading.
@vivienne I guess I unfortunately have to stick with the old plugin for now If you don't have the time or intention for the ongoing development. 
Anyway, thanks for your work and sharing with the community.

**Comment by dsully** [comment]
I've noticed that bug too, and is something I'll be looking at fixing. Basically the status isn't being pulled from the state of the fan (say you use the Haiku app or a remote control) into Homebridge.

**Comment by vivienne** [comment]
Thanks for the feedback - I updated both the fan and light accessories to pull status asynchronously. This should show up in npm as v2.1.0.

I still need to update the light accessory to get the colorTemperature refreshed asynchronously, but power/brightness (lightbulb) and power/speed (fan) should now get refreshed automatically, even if you change the controls using a method other than HomeKit. 

I've tested it on the lightbulb but not the fan. Can you give it a try and let me know if it's working for you?

**Comment by vivienne** [comment]
Closing this issue as the original problem is fixed - please open a new one if you have new issues.
