### ISSUE TITLE
Missing device type: FAN,LSERIES

### ISSUE THREAD

**Issue by sjschneider** [vivienne/homebridge-haiku-senseme#4]
Discovery system is unable to process Haiku L-Series device: https://www.bigassfans.com/fans/haiku-l/

Please see below for error log.  It looks like this may be a string matching issue.  Note that the L-Series has an integrated LED.

[10/20/2020, 14:59:55] Homebridge is running on port 51084.
[10/20/2020, 14:59:56] [Haiku] Found a device: Office Fan / FAN,LSERIES / 192.168.254.71 / 20:F8:5E:27:99:FD
[10/20/2020, 14:59:56] [Haiku] Not sure what to do with this device type: Office Fan (FAN,LSERIES)

**Comment by vivienne** [comment]
I did a quick fix for the string matching issue (v2.1.1), so you should at least get the fan control now. I'll need to work on the light control for fans that have an integrated light, but don't have a device to test it on. I'll create a beta build when I have something that I think might work (feel free to submit a PR if you have something that works). Thanks for testing this out!

**Comment by sjschneider** [comment]
Excellent -- I can confirm that all my fans are detected, including the L-Series.  I would be happy to test out the functionality with the integrated light when the change is available.  Unfortunately, it is not likely that I will have time to edit the code myself anytime soon, but I could maybe take a look if you could provide some guidance on what is needed for the change.  Thanks very much!

**Comment by vivienne** [comment]
Closing this issue, for the fan + integrated light support we can refer to https://github.com/vivienne/homebridge-haiku-senseme/issues/7
