### ISSUE TITLE
Remember last speed setting?

### ISSUE THREAD

**Issue by StephenShamakian** [vivienne/homebridge-haiku-senseme#8]
This is great! I built something similar to this in HomeSeer to send the packets to the fans to control them via HomeBidge but it didn't poll for updates. This does! :) 

I see in another issue you are working on adding light support! That was going to be another request I had.

But is it at all possible to add the ability to remember the last speed setting the fan was on? So when you turn it on and off it goes back to the setting that was last set? Much how lights work in HomeKit.

Thanks!

**Comment by vivienne** [comment]
Let me think about how to do this, I think it's possible but it's difficult for me to do any testing since I don't have a fan myself. If you're okay with being my guinea pig I will work on this. Thank you for your ideas!

**Comment by StephenShamakian** [comment]
@vivienne Sure! I actually installed the the beta right after I posted this and it has been much better as it changes what happens when you short press on the fan accessory. Instead of just turning the fan on it brings up the long press screen where you specifically pick the speed or the light level. This kind of fixes the issue indirectly I guess. :)

**Comment by vivienne** [comment]
@StephenShamakian That's good! If that works for you, do you mind if I close this issue?

**Comment by StephenShamakian** [comment]
@vivienne That's fine! The v3 seems to have solved this problem for me!
